### ISSUE TITLE
Question, is posible to add "is running" and get wich port using?

### ISSUE THREAD

**Issue by sefirosweb** [imharvol/mineflayer-web-inventory#10]
Hello!
Is very great this plugin,
I'm trying to get an option if the plugin is already running and which port is listening, it is possible to add?

**Comment by imharvol** [comment]
Hey, thanks for the suggestion!

I think this is part of a change that should have been made some time ago: add the option to start/close the web server.
It's now implemented in `mineflayer-web-inventory@1.2.0`. This allows you to:
- Check the port using: bot.webInventory.options.port
- Check if the web server is running: bot.webInventory.isRunning
- Start/Stop the server: bot.webInventory.start([cb]), bot.webInventory.stop([cb])

Hope this is what you meant :)
