### ISSUE TITLE
CORS error on 1.6.0

### ISSUE THREAD

**Issue by sefirosweb** [imharvol/mineflayer-web-inventory#24]
Hello after update to 1.6.0 (from 1.4.0) I have CORS error when load .css and .js files

Also i see soem files not found

![image](https://user-images.githubusercontent.com/20754836/128612806-209f6e8b-1d8f-42b8-a217-e42b852a0bd3.png)

![image](https://user-images.githubusercontent.com/20754836/128612810-3337b11a-c743-4306-8b48-4ce216dac19a.png)

*I have updated mineflayer to laetst version 3.9.0

**Comment by imharvol** [comment]
Probably related to https://github.com/imharvol/mineflayer-web-inventory/issues/23 while it's solved, try using the solution mentioned there

**Comment by sefirosweb** [comment]
Hi seems is related,

I installed the remove-path version
```npm i https://github.com/imharvol/mineflayer-web-inventory.git#remove-path```
this version don't show cors error

**Comment by sefirosweb** [comment]
After a few test I reinstalled 1.6.0 and now no shows error, 

I don't know why now works but seems is an issue from cache or random error from Express

I close the ticket because now works.. and i cant reproduce the error

Best!
