### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The last argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by ulcuber** [imharvol/mineflayer-web-inventory#33]
Methods:
```js
bot.webInventory.start()
bot.webInventory.stop()
```
maybe not return a Promise because they callbackified.

Need to update docs to use like this:
```js
bot.webInventory.start(() => {})
bot.webInventory.stop(() => {})
```

**Comment by imharvol** [comment]
The documentation doesn't mention callbacks so now that mineflayer 4 uses promises, lets just use a promise
