### ISSUE TITLE
On install prod dependencies breaks the installatión

### ISSUE THREAD

**Issue by sefirosweb** [imharvol/mineflayer-web-inventory#37]
Hello i found a bit glitch,

On my project when i'm going to install only production dependencies only, this packages breaks the installation:

![image](https://user-images.githubusercontent.com/20754836/222279212-9d65583d-9390-4fe2-8ae9-c28e219d88b5.png)

This package is in production dependencies because I use them in prod
![image](https://user-images.githubusercontent.com/20754836/222279395-2e630917-5142-4267-9944-d93073917298.png)

**Comment by imharvol** [comment]
Thanks! Should be fixed in mineflayer-web-inventory@1.8.4

**Comment by sefirosweb** [comment]
Thanks it works!
